### ISSUE TITLE
OptionalAbstractKeyword false positive

### ISSUE THREAD

**Issue by benwicks** [arturbosch/detekt#783] opened 2018-03-09 19:20 UTC
I don't think detekt should be failing with `OptionalAbstractKeyword` at the `dependency` abstract function in my case. What do you think?

```
@Subcomponent.Builder
abstract class Builder : AndroidInjector.Builder<MyController>() {

    @BindsInstance
    abstract fun dependency(dependency: DependencyType)

    override fun seedInstance(instance: MyController) {
        dependency(instance.args.get(MyController.KEY_DEPENDENCY)) as DependencyType
    }
}
```

**Comment by schalkms** [comment] 2018-03-10 15:16
I can't reproduce it. What detekt version are you using?

**Comment by arturbosch** [comment] 2018-03-25 13:17
Can't reproduce on master (and also rc6-4) closing.

**Comment by benwicks** [comment] 2018-03-26 20:56
I was on rc6-3 and it is still failing with rc6-4. I apologize, I did not include the wrapping interface in my reproduction code sample. Here is a more complete sample:
```
@Subcomponent
internal interface Component : AndroidInjector<MyController> {

    @Subcomponent.Builder
    abstract class Builder : AndroidInjector.Builder<MyController>() {

        @BindsInstance
        abstract fun dependency(dependency: DependencyType)

        override fun seedInstance(instance: MyController) {
            dependency(instance.args.get(MyController.KEY_DEPENDENCY)) as DependencyType
        }
    }
}
```

**Closed** 2018-03-30 08:46 UTC
Labels: bug, rules, waiting for verification
