### ISSUE TITLE
Should enums be a data classes?

### ISSUE THREAD

**Issue by adauvalter** [arturbosch/detekt#479] opened 2017-10-10 06:51 UTC
I have an enum and detekt fails with an error: `UseDataClass` Could we exept enums from check for that?

**Comment by Mauin** [comment] 2017-10-10 06:59
Sounds like a good idea. Either excluding enums by default or at least giving a configuration option to exclude them.

Could you post a code snippet that is showing the violation?

**Comment by arturbosch** [comment] 2017-10-10 07:09
That's already fixed in master. New release should come in a few days ^^ - duplicate of #435

**Closed by arturbosch** 2017-10-10 07:09 UTC
Labels: hacktoberfest, improvement, rules
