### ISSUE TITLE
main.xml does not exist

### ISSUE THREAD

**Issue by jcornaz** [arturbosch/detekt#1757] opened 2019-07-05 09:18 UTC
## Expected Behavior
Since #1329, If there are sources in the root project of a multiproject setup, then a consolidated reports should be generated. And anyway the build should at least pass.

## Observed Behavior
The build fail with:

```
Execution failed for task ':detekt'.
> C:\Workspace\tptool\backend\code-generator\build\reports\detekt\main.xml does not exist
```

## Steps to Reproduce
1. Create a multiproject build *without sources in the root project*
2. Run `gradlew detekt` and make sure it passes
3. Add a source in the root project
4. Run `gradlew detekt` again.
5. Observe the build failure

## Context
I am trying to generate a consolidated report.

## Your Environment
* Version of detekt used: 1.0.0-RC16
* Version of Gradle used (if applicable): 5.4.1
* Operating System and version: Windows 10

**Comment by cortinico** [comment] 2019-07-05 15:37
Looks like a duplicate of #1685

**Comment by marschwar** [comment] 2019-07-10 20:46
Thank you for reporting this. I managed to reproduce it in one of the tests. All that needs to be done is to apply the kotlin plugin to all projects. Then the new sourceset mechanism kicks in.

`DetektTaskMultiModuleConsolidationTest`

```
            val mainBuildFileContent: String = """
                |buildscript { 
                |   repositories {
                |       mavenCentral()
                |   }
                |   dependencies {
                |       classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.30")
                |   }
                |}
                |plugins {
                |   id "io.gitlab.arturbosch.detekt"
                |}
                |
                |allprojects {
                |    repositories {
                |        mavenLocal()
                |        jcenter()
                |    }
                |    apply plugin: 'kotlin'
                |    
                |    detekt {
                |       debug = true
                |    }
                |}
                |subprojects {
                |    apply plugin: "io.gitlab.arturbosch.detekt"
                |}
                """.trimMargin()
```

@arturbosch We need to fix the root cause of this issue. #1763 would only cause the consolidation to not work correctly.

**Closed** 2019-07-14 17:58 UTC
Labels: duplicate
