### ISSUE TITLE
compileAndLint treat top level functions as local functions

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2206] opened 2019-12-28 10:56 UTC
## Expected Behavior
This code should pass:

```kotlin
UnusedPrivateClass().compileAndLint("private fun a() = Unit")
```

## Observed Behavior
It fails with this error: 
```
Caused by: javax.script.ScriptException: Error: error: modifier 'private' is not applicable to 'local function'
private fun a() = Unit
^

	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
	at io.gitlab.arturbosch.detekt.test.KotlinScriptEngine.compile(KotlinScriptEngine.kt:18)
	... 10 more
```

## Steps to Reproduce
just copy&paste the code I said at any test

## Context
I'm moving some tests from lint to compileAndLint. And I'm getting this type of errors. I know how to workaround them but I think that this is a bug. 

Why does the compiler treat that function as a local function instead of top level function? Maybe we are missing some edge cases in our tests because of this.

## Your Environment
* Version of detekt used: `master` (1.3.0)

**Comment by schalkms** [comment] 2019-12-30 17:06
This is not a bug. When using KotlinScripts (`.kts`) you can't declare a function `private`. This behavior is by design. I'm closing this issue, since there's nothing we can do about that.

**Closed by schalkms** 2019-12-30 17:06 UTC
Labels: rules
