### ISSUE TITLE
Spek Rule: duplicated test case message

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#572] opened 2017-11-24 18:30 UTC
If multiple it test cases in the same given or describe function have the same name only one of them gets executed.

**Comment by vanniktech** [comment] 2017-11-25 00:50
This will be fixed in spek v2

**Comment by schalkms** [comment] 2017-11-25 07:05
Okay. Thanks for the hint. Does it print a warning or does it throw a compiler error in v2?

**Comment by vanniktech** [comment] 2017-11-25 07:43
It just works.

**Comment by schalkms** [comment] 2017-11-25 07:45
Okay! :)
Do you have a reference link or something?
Then I’ll close this.

**Comment by vanniktech** [comment] 2017-11-25 09:53
It was mentioned somewhere in @artem-zinnatullin talk at Kotlinconf about spek.

**Comment by artem-zinnatullin** [comment] 2017-11-26 08:48
Yep, anyways doesn't look right to put framework/library specific checks into generic checker :)

**Comment by arturbosch** [comment] 2017-11-26 09:04
When ist spek 2.0 ETA? Doesnt it make sense to provide such a check for people using spek 1.x? Until the issue ist fixed and the adoption rate is high enough?

We wont include the check into the standard rule set though.

**Comment by arturbosch** [comment] 2017-12-22 20:41
Closing this on as its unlikely to create a new rule set for testing frameworks in the near future.

**Closed by arturbosch** 2017-12-22 20:41 UTC
Labels: feature, rules

**Comment by schalkms** [comment] 2017-12-22 20:43
I agree on this.
