### ISSUE TITLE
Feature Request: Ignore MaxLineLength for imports

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#125] opened 2017-06-23 22:45 UTC
I'd like to be able to enforce a max line length for everything except imports, if possible.

**Comment by Mauin** [comment] 2017-06-24 07:37
This seems to be a duplicate of #111 where we already discussed doing exactly this. It's currently planned for M12.2.

**Closed** 2017-06-25 20:31 UTC
