### ISSUE TITLE
Update rule descriptions and adapt debt minutes

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#475] opened 2017-10-07 20:13 UTC
In my opinion the rule description should follow a simple template.
This helps to make the violations more understandable for the user.

I think the debt minutes should also be updated accordingly.

**Comment by Mauin** [comment] 2017-10-08 14:25
What kind of template do you suggest? In my opinion the description should be as fine grained as possible to give the user a clear understanding of what detekt is not happy about in that piece of code. (See also #273)

**Comment by schalkms** [comment] 2017-10-09 10:18
I agree. I think there should be at least.
- What caused the violation (generic approach)
- What result the code causes (think of **!!** for example)
- How the user can fix it

I am of course open to improvements.

**Comment by Mauin** [comment] 2017-10-09 10:24
In general I really like how Android lint handles Issues and their description. 
Each issue has a short name, a long name, and a detailed description explaining the rationale of the Issue. This description explains why the issue is an issue and how it can be fixed.

Additionally every time an `Issue` is reported a `message` is attached which explains the specific case. This message refers to the specific code in most of the cases to point out what exactly is wrong.

As an example: 
- [The Android Lint Issue](https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/LogDetector.java#59)
- [How the issue is reported](https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/LogDetector.java#145)

**Comment by schalkms** [comment] 2017-10-09 11:46
Ok. I am more a fan of the sonarlint implementation but I can live with others as well. I like the separate message field. I don't want to mix the specific code details with the description of the rule.

**Comment by arturbosch** [comment] 2017-10-09 19:26
In another issue we discussed the detailed generic description with an example above the rule as KDoc. From this kdoc we could generate like md files and display them all together on a webpage?

The short name is basically our `RuleName`. The long name is kinda obvious if the short name is good. With the detailed kdoc, the issue description should be generic (for sonar rule profiles) and overridden if needed for a specific finding.

**Comment by schalkms** [comment] 2017-10-09 19:35
Good idea! I like it. This is already documented in #343
I would also combine them with compliant and noncompliant code snippets. However, I would write this snippets in a separate file.

**Comment by arturbosch** [comment] 2017-10-09 19:39
Yes, I think @vanniktech mentioned the compliant and noncompliant code snippets ^^ (or maybe you oO, I give you both credits ^^)

**Comment by vanniktech** [comment] 2017-10-09 19:51
I think it was him because I don't know what you're talking about :D

**Comment by Mauin** [comment] 2018-02-09 07:29
With the KDoc changes, generated documentation, compliant/non-compliant code examples in the KDoc as well as concrete messages for `CodeSmell`s I will close this now. Feel free to re-open this if you can think of more cases we can document for rules.

**Closed by Mauin** 2018-02-09 07:29 UTC
Labels: documentation
